version: "3.7"

x-service-base: &service-base
  image: cloudreactor-ecs-quickstart
  build:
    context: ./
  volumes:
    - ./src/:/home/appuser/src/
    - ./deploy/files/proc_wrapper_1.3.0.py:/home/appuser/proc_wrapper.py
    - ./deploy/files/.env.dev:/home/appuser/.env

x-dev-base: &dev-base
  <<: *service-base
  image:  cloudreactor-ecs-quickstart-dev
  build:
    context: ./
    dockerfile: Dockerfile-dev
  volumes:
    - ./src/:/home/appuser/src/
    - ./tests/:/home/appuser/tests/
    - ./deploy/files/.env.dev:/home/appuser/.env
    - ./mypy.ini:/home/appuser/mypy.ini

x-pip-compile-base: &pip-compile-base
  image: cloudreactor-pip-tools
  build:
    context: ./
    dockerfile: tools/pip-tools/Dockerfile
  volumes:
    - ./:/work

services:
  task_1:
    <<: *service-base
    command: python src/task_1.py

  file_io:
    <<: *service-base
    command: python src/file_io.py

  web_server:
    <<: *service-base
    command: flask run -p 7070 --host=0.0.0.0
    environment:
      FLASK_APP: "src/web_server.py"
    ports:
      - "7070:7070"

  postgres_to_snowflake:
    <<: *service-base
    command: python src/postgres_to_snowflake.py

  # Not a deployed task, here for debugging your Docker build.
  shell:
    <<: *service-base
    command: bash

  pytest:
    <<: *dev-base

  pytest-cov:
    <<: *dev-base
    command: pytest --cov=src

  pylint:
    <<: *dev-base
    command: pylint --rcfile=src/.pylintrc src

  mypy:
    <<: *dev-base
    command: mypy src

  safety:
    <<: *dev-base
    command: safety check

  dev-shell:
    <<: *dev-base
    command: bash

  pip-compile:
    <<: *pip-compile-base

  pip-compile-dev:
    <<: *pip-compile-base
    command: dev-requirements.in --output-file dev-requirements.txt

  # Check your Dockerfile against best-practices:
  # See https://github.com/hadolint/hadolint
  hadolint:
    image: hadolint/hadolint
    volumes:
      - ./Dockerfile:/mnt/Dockerfile
      - ./.hadolint.yaml:/mnt/.hadolint.yaml
    command: /bin/hadolint --config /mnt/.hadolint.yaml /mnt/Dockerfile
